# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReconZA.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QHBoxLayout, QPushButton, QTableWidgetItem, QHBoxLayout, QWidget, QMessageBox, QFileDialog, QListWidget, QCheckBox
from AddNewEntry import Ui_EntryDialog
from UpdateEntry import Ui_update_EntryDialog
from ReconEntry2 import Ui_ReconDialog


import mysql.connector
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from reportlab.lib import colors


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1299, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ReconInfo = QtWidgets.QTableWidget(self.centralwidget)
        self.ReconInfo.setGeometry(QtCore.QRect(10, 200, 1241, 600))
        self.ReconInfo.setStyleSheet("QHeaderView::section{\n"
"    font-weght:bold;\n"
"    background-color:black;\n"
"    color: white;\n"
"}\n"
"TabelWidget{\n"
"    alternate-background-color: rgb(176, 237, 251);\n"
"    background-color: rgb(244, 249, 250);\n"
"}")
        self.ReconInfo.setObjectName("ReconInfo")
        self.ReconInfo.setColumnCount(8)
        self.ReconInfo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ReconInfo.setHorizontalHeaderItem(7, item)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(690, 30, 361, 71))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.cashBookLineEdit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.cashBookLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.cashBookLineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.cashBookLineEdit.setFont(font)
        self.cashBookLineEdit.setObjectName("cashBookLineEdit")
        self.verticalLayout_3.addWidget(self.cashBookLineEdit)
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget, textChanged = lambda: self.search_accCode())
        self.searchLineEdit.setGeometry(QtCore.QRect(410, 120, 311, 41))
        self.searchLineEdit.setMinimumSize(QtCore.QSize(0, 41))
        self.searchLineEdit.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setText("")
        self.searchLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 671, 74))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.transactionComboBox_H = QtWidgets.QComboBox(self.layoutWidget, currentIndexChanged = lambda: self.load_entry_info())
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.transactionComboBox_H.setFont(font)
        self.transactionComboBox_H.setStyleSheet("QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius:8px;\n"
"    padding-left:15px;\n"
"    height:35px;\n"
"    padding: 1px 18px 3px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    selection-background-color: rgb(41, 128, 185);\n"
"}")
        self.transactionComboBox_H.setObjectName("transactionComboBox_H")
        self.transactionComboBox_H.addItem("")
        self.transactionComboBox_H.addItem("")
        self.transactionComboBox_H.addItem("")
        self.verticalLayout_7.addWidget(self.transactionComboBox_H)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.transactionComboBox__H = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.transactionComboBox__H.setFont(font)
        self.transactionComboBox__H.setStyleSheet("QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius:8px;\n"
"    padding-left:15px;\n"
"    height:35px;\n"
"    padding: 1px 18px 3px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    selection-background-color: rgb(41, 128, 185);\n"
"}")
        self.transactionComboBox__H.setObjectName("transactionComboBox__H")
        self.transactionComboBox__H.addItem("")
        self.transactionComboBox__H.addItem("")
        self.transactionComboBox__H.addItem("")
        self.verticalLayout_8.addWidget(self.transactionComboBox__H)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 120, 381, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addEntryBtn_1 = QtWidgets.QPushButton(self.layoutWidget1, clicked = lambda: self.open_addEntry_dialog())
        self.addEntryBtn_1.setMinimumSize(QtCore.QSize(0, 41))
        self.addEntryBtn_1.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.addEntryBtn_1.setFont(font)
        self.addEntryBtn_1.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(52, 212, 129);\n"
"    color: white;\n"
"    border:none;\n"
"    border-radius:bold;\n"
"    font-size:15px\n"
"}")
        self.addEntryBtn_1.setObjectName("addEntryBtn_1")
        self.horizontalLayout_2.addWidget(self.addEntryBtn_1)
        self.addEntryBtn_2 = QtWidgets.QPushButton(self.layoutWidget1, clicked = lambda: self.open_ReconEntry_dialog())
        self.addEntryBtn_2.setMinimumSize(QtCore.QSize(0, 41))
        self.addEntryBtn_2.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.addEntryBtn_2.setFont(font)
        self.addEntryBtn_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(52, 212, 129);\n"
"    color: white;\n"
"    border:none;\n"
"    border-radius:bold;\n"
"    font-size:15px\n"
"}")
        self.addEntryBtn_2.setObjectName("addEntryBtn_2")
        self.horizontalLayout_2.addWidget(self.addEntryBtn_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(870, 120, 381, 43))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ExportExcel_2 = QtWidgets.QPushButton(self.layoutWidget_2, clicked = lambda: self.export_to_excel_reconTable())
        self.ExportExcel_2.setMinimumSize(QtCore.QSize(0, 41))
        self.ExportExcel_2.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.ExportExcel_2.setFont(font)
        self.ExportExcel_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(52, 212, 129);\n"
"    color: white;\n"
"    border:none;\n"
"    border-radius:bold;\n"
"    font-size:15px\n"
"}")
        self.ExportExcel_2.setObjectName("ExportExcel_2")
        self.horizontalLayout_3.addWidget(self.ExportExcel_2)
        self.ExportPDF = QtWidgets.QPushButton(self.layoutWidget_2, clicked = lambda: self.export_to_pdf())
        self.ExportPDF.setMinimumSize(QtCore.QSize(0, 41))
        self.ExportPDF.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.ExportPDF.setFont(font)
        self.ExportPDF.setStyleSheet("QPushButton{\n"
"    \n"
"\n"
"    background-color: rgb(255, 0, 0)    ;\n"
"    color: white;\n"
"    border:none;\n"
"    border-radius:bold;\n"
"    font-size:15px\n"
"}")
        self.ExportPDF.setObjectName("ExportPDF")
        self.horizontalLayout_3.addWidget(self.ExportPDF)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1299, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/newspaper--pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/folder-network-horizontal-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_2.setIcon(icon1)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionImport_2 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/table-import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport_2.setIcon(icon2)
        self.actionImport_2.setObjectName("actionImport_2")
        self.actionExport_2 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/property-export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_2.setIcon(icon3)
        self.actionExport_2.setObjectName("actionExport_2")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon4)
        self.actionPrint.setObjectName("actionPrint")
        self.actionReport_PDF = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/report-share.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport_PDF.setIcon(icon5)
        self.actionReport_PDF.setObjectName("actionReport_PDF")
        self.actionReport_Excel = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/report-excel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport_Excel.setIcon(icon6)
        self.actionReport_Excel.setObjectName("actionReport_Excel")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../../Engineering Investigation and Problem Solving/fugue-icons-3.5.6/icons/question-octagon-frame.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon7)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addAction(self.actionImport_2)
        self.menuFile.addAction(self.actionExport_2)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExit_2)
        self.menuReports.addAction(self.actionReport_PDF)
        self.menuReports.addAction(self.actionReport_Excel)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    #Connect to mysql server and create database if it does not exist
        self.create_connection()
        
    # Create Entry Table
        self.create_EntryTable()
        
    # Open add entry dialog not functional for this app
    
    # Load entry information to QTable
        self.load_entry_info()
        #self.select_transaction.currentIndexChanged.connect(self.load_entry_info())

    
    #def open_newEntry_dialog(self):
        
     #   from EntryDialog import Ui_EntryDialog
        
        #Instantiate and show the dialog
      #  addEntry_dialog = Ui_EntryDialog(self)
      # result = addEntry_dialog.exec() # This will open the entry dialog
        
      #  if result == Ui_EntryDialog.accepted:
            # if the dialog was accepted (User clicked add New Entry button)
      #      pass
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ReconZA"))
        item = self.ReconInfo.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.ReconInfo.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Acc Details"))
        item = self.ReconInfo.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Acc Code"))
        item = self.ReconInfo.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Reference no"))
        item = self.ReconInfo.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Transaction Type"))
        item = self.ReconInfo.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.ReconInfo.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Recon"))
        item = self.ReconInfo.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Action"))
        self.label_12.setText(_translate("MainWindow", "Cash Book Balance"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Search Acc Code"))
        self.label_8.setText(_translate("MainWindow", "Transaction Type"))
        self.transactionComboBox_H.setItemText(0, _translate("MainWindow", "Select Transaction Type"))
        self.transactionComboBox_H.setItemText(1, _translate("MainWindow", "Credit"))
        self.transactionComboBox_H.setItemText(2, _translate("MainWindow", "Debit"))
        self.label_9.setText(_translate("MainWindow", "Reconcilliation"))
        self.transactionComboBox__H.setItemText(0, _translate("MainWindow", "Show all"))
        self.transactionComboBox__H.setItemText(1, _translate("MainWindow", "Reconciled Items"))
        self.transactionComboBox__H.setItemText(2, _translate("MainWindow", "Hide Reconciled Items"))
        self.addEntryBtn_1.setText(_translate("MainWindow", "Add Entry"))
        self.addEntryBtn_2.setText(_translate("MainWindow", "Reconcile Entry"))
        self.ExportExcel_2.setText(_translate("MainWindow", "Export to Excel"))
        self.ExportPDF.setText(_translate("MainWindow", "Export to PDF"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "New"))
        self.actionImport.setText(_translate("MainWindow", "Open"))
        self.actionExport.setText(_translate("MainWindow", "Import"))
        self.actionClose.setText(_translate("MainWindow", "Export"))
        self.actionExit.setText(_translate("MainWindow", "Print Setup"))
        self.actionGenerate.setText(_translate("MainWindow", "Generate Report"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionImport_2.setText(_translate("MainWindow", "Import"))
        self.actionExport_2.setText(_translate("MainWindow", "Export"))
        self.actionPrint.setText(_translate("MainWindow", "Print Setup"))
        self.actionReport_PDF.setText(_translate("MainWindow", "Report PDF"))
        self.actionReport_Excel.setText(_translate("MainWindow", "Report Excel"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))


# Create database Connection

    def create_connection(self):
        #replace these with your actual MySql server details
        host_name = "localhost"
        user_name = "root"
        mypassword = ""
        database_name = "reconcile"
        
        #establish a connection to MySQL server
        self.mydb = mysql.connector.connect(
            host = host_name,
            user = user_name,
            password = mypassword,
        )
        #Create a cursor to execute sql queries
        cursor = self.mydb.cursor()
        
        #Create the database if it does not exist
        cursor.execute(f'CREATE DATABASE IF NOT EXISTS {database_name}')
        
        #connect to the created database
        self.mydb = mysql.connector.connect(
            host = host_name,
            user = user_name,
            password = mypassword,
            database = database_name
        )
        
        return self.mydb
        
        
    #Create Entry Table
    
    def create_EntryTable(self):
        
        #create a cursor for executing sql queries
        cursor = self.create_connection().cursor()
        
        #Query
        create_EntryTable_query = """CREATE TABLE IF NOT EXISTS recon_t(date DATE, accDetails VARCHAR(255), accCode VARCHAR(50), reference_number VARCHAR(15) PRIMARY KEY, transaction_type VARCHAR(10),amount DECIMAL(10, 2))"""
            
        cursor.execute(create_EntryTable_query)
        
        #Commit changes and close the connection
        self.mydb.commit()
        self.mydb.close()
        
    # Open Dialog for insering new Entry

    def open_addEntry_dialog(self):
        # opens the AddEntry Dialog
        EntryDialog = QtWidgets.QDialog()
        ui = Ui_EntryDialog()
        ui.setupUi(EntryDialog)
        EntryDialog.show()
        EntryDialog.exec_()
        
        #if EntryDialog.exec_() == Ui_EntryDialog.Accepted:
            
        self.load_entry_info()

    def open_ReconEntry_dialog(self):
        # opens the Recon Entry Dialog
        ReconDialog = QtWidgets.QDialog()
        ui = Ui_ReconDialog()
        ui.setupUi(ReconDialog)
        ReconDialog.show()
        ReconDialog.exec_()
            
        #if EntryDialog.exec_() == Ui_EntryDialog.Accepted:
                
        self.load_entry_info()
            
            
    # Load entry information QTABLE
    def load_entry_info(self):
        #clear existing data in the table
        self.ReconInfo.setRowCount(0)
        
        
        #fetch data based on selected transaction type and Reconciliation
        selected_transaction = self.transactionComboBox_H.currentText()
        #selected_recon = self.transactionComboBox_2.currentText()
        data  = self.get_data_from_table(selected_transaction)#, selected_recon)

        #Populate table with the filtered data
        for row_index, row_data in enumerate(data):
            self.ReconInfo.insertRow(row_index)
            for col_index, cell_data in enumerate(row_data):
                item = QTableWidgetItem(str(cell_data))
                self.ReconInfo.setItem(row_index, col_index, item)
                
                # Create a custom widget with two horizontally lined up buttons for the action column
                double_button_widget = DoubleButtonWidgetsEntry(row_index, row_data)
                
                # Create a checkbox widget 
                checkbox_widget = CheckBoxWidget(row_index, row_data)
                
                # Set this custom widget with two buttons as the cell widget for the action column
                self.ReconInfo.setCellWidget(row_index, 7, double_button_widget)
                self.ReconInfo.setRowHeight(row_index, 50)
                
                #Set this custom widget with one checkbox
                self.ReconInfo.setCellWidget(row_index, 6, checkbox_widget)
                self.ReconInfo.setRowHeight(row_index, 50)
                
                
        self.calculate_net_balance()        
                
    def get_data_from_table(self, transaction_filter):#you can add recon_filter
        
        cursor = self.create_connection().cursor()
        
        #construct the sql query based on the selected filter
        query = f"""SELECT date, accDetails, accCode, reference_number, transaction_type,amount FROM recon_t WHERE 
                   ('{transaction_filter}' = 'SELECT TRANSACTION_TYPE' OR transaction_type = '{transaction_filter}')
                   """
                   #('{recon_filter}' = 'SELECT RECON' OR recon = '{transaction_filter}')
                   
        cursor.execute(query)
        data = cursor.fetchall()
        return data

#Double button class

    def search_accCode(self):
        
        #Cear previous table results
        self.ReconInfo.setRowCount(0)
        
        # Get the search query from Qlinedit
        search_query = self.searchLineEdit.text()
        
        #Execute the SQL Query
        cursor = self.create_connection().cursor()
        
        #construct the sql query based on the selected filter
        sql_query = f"""SELECT date, accDetails, accCode, reference_number, transaction_type,amount FROM recon_t WHERE 
                   accCode LIKE '%{search_query}%'
                   """
        cursor.execute(sql_query)
        results = cursor.fetchall()
        
        #Populate table with the filtered data
        for row_index, row_data in enumerate(results):
            self.ReconInfo.insertRow(row_index)
            for col_index, cell_data in enumerate(row_data):
                item = QTableWidgetItem(str(cell_data))
                self.ReconInfo.setItem(row_index, col_index, item)
                
                # Create a custom widget with two horizontally lined up buttons for the action column
                double_button_widget = DoubleButtonWidgetsEntry(row_index, row_data)
                
                # Create a checkbox widget 
                checkbox_widget = CheckBoxWidget(row_index, row_data)
                
                # Set this custom widget with two buttons as the cell widget for the action column
                self.ReconInfo.setCellWidget(row_index, 7, double_button_widget)
                self.ReconInfo.setRowHeight(row_index, 50)
                
                #Set this custom widget with one checkbox
                self.ReconInfo.setCellWidget(row_index, 6, checkbox_widget)
                self.ReconInfo.setRowHeight(row_index, 50)
        
    # Excel Export
    
    def export_to_excel_reconTable(self):
        
        #Convert QTableWidget to pandas Dataframe
        try:
            # Convert QTableWidget to pandas DataFrame
            data = []

            # Extract headers from the QTableWidget
            headers = [self.ReconInfo.horizontalHeaderItem(col).text() if self.ReconInfo.horizontalHeaderItem(col) else f"Column {col+1}" for col in range(self.ReconInfo.columnCount())]

            # Extract data from the QTableWidget
            for row in range(self.ReconInfo.rowCount()):
                row_data = [
                    self.ReconInfo.item(row, col).text() if self.ReconInfo.item(row, col) else "" 
                    for col in range(self.ReconInfo.columnCount())
                ]
                data.append(row_data)

            # Create a pandas DataFrame
            df = pd.DataFrame(data, columns=headers)

            # Exclude the last column before exporting
            df_filtered = df.iloc[:, :-1]

            # Open QFileDialog to get the file path
            file_dialog = QFileDialog()
            file_path, _ = file_dialog.getSaveFileName(self.MainWindow, "Save Excel File", "", "Excel Files (*.xlsx);;All Files (*)")

            if file_path:
                # Ensure the file has a .xlsx extension
                if not file_path.endswith(".xlsx"):
                    file_path += ".xlsx"

                # Save filtered DataFrame to Excel file
                df_filtered.to_excel(file_path, index=False)
                QMessageBox.information(self.MainWindow, "Success", f"Table exported successfully to {file_path}")
            else:
                QMessageBox.warning(self.MainWindow, "Cancelled", "Export operation was cancelled.")

        except Exception as e:
            QMessageBox.critical(self.MainWindow, "Error", f"An error occurred: {str(e)}")

        
    def export_to_pdf(self):
        try:
            # Open QFileDialog to get the file path
            file_dialog = QFileDialog()
            file_path, _ = file_dialog.getSaveFileName(self.MainWindow, "Save PDF File", "", "PDF Files (*.pdf);;All Files (*)")
        
            if file_path:
                # Ensure the file has a .pdf extension
                if not file_path.endswith(".pdf"):
                    file_path += ".pdf"
                
                # Create a PDF Document
                pdf_document = SimpleDocTemplate(file_path, pagesize=letter)
                
                # Extract column count
                column_count = self.ReconInfo.columnCount()
                
                # Extract headers from the QTableWidget
                headers = [self.ReconInfo.horizontalHeaderItem(col).text() for col in range(column_count)]
                
                # Extract data from the QTableWidget
                data = [headers]
                for row in range(self.ReconInfo.rowCount()):
                    row_data = [
                        self.ReconInfo.item(row, col).text() if self.ReconInfo.item(row, col) else "" 
                        for col in range(column_count)
                    ]
                    data.append(row_data)
                
                # Create a PDF Table
                pdf_table = Table(data)
                
                # Apply styles to the table
                style = TableStyle([
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, 0), 14),  # Larger font for the header
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 12),  # Highlight header row
                    ('GRID', (0, 0), (-1, -1), 1, colors.black),
                    
                ])
                pdf_table.setStyle(style)
                
                # Build the PDF document
                pdf_document.build([pdf_table])
                
                # Display success message
                QMessageBox.information(self.MainWindow, "Success", f"Table exported successfully to {file_path}")
            else:
                QMessageBox.warning(self.MainWindow, "Cancelled", "Export operation was cancelled.")
        except Exception as e:
            QMessageBox.critical(self.MainWindow, "Error", f"An error occurred: {str(e)}")
        
    def calculate_net_balance(self):
        try:
            # Establish connection
            connection = self.create_connection()
            if connection is None:
                return
            
            cursor = connection.cursor()
            
            # Query to sum amounts by transaction type
            query = """
                SELECT 
                    SUM(CASE WHEN transaction_type = 'Credit' THEN amount ELSE 0 END) AS total_credit,
                    SUM(CASE WHEN transaction_type = 'Debit' THEN amount ELSE 0 END) AS total_debit
                FROM recon_t
            """
            cursor.execute(query)
            result = cursor.fetchone()
            
            total_credit = result[0] if result[0] is not None else 0
            total_debit = result[1] if result[1] is not None else 0
            
            # Calculate net balance
            net_balance = total_credit - total_debit
            
            cursor.close()
            connection.close()
            
            # Update the cashBookLineEdit with the net balance
            self.cashBookLineEdit.setText(f"R{net_balance:,.2f}")
            
            return net_balance
        

        except mysql.connector.Error as err:
            print(f"Error: {err}")
            QMessageBox.critical(None, "Database Error", f"Error: {err}")
            return None

class CheckBoxWidget(QWidget):
    def __init__(self, row_index, row_data):
        super().__init__()
        
        # Store the row index and row data as an instance in variables
        self.row_index = row_index
        self.row_data = row_data
        
        # Get entry variables from the tuple
        self.entry_details = self.row_data[1]
        self.reference_number = self.row_data[3]
        
        layout = QHBoxLayout(self)
        
        #Checkbox
        self.check_box = QCheckBox(self)
        self.check_box.setStyleSheet("margin-left:50%; margin-right:50%;")

   # def match:
        
        
        
class DoubleButtonWidgetsEntry(QWidget): 
    def __init__(self, row_index, row_data):
        super().__init__()
        
        # Store the row index and row data as an instance in variables
        self.row_index = row_index
        self.row_data = row_data
        
        # Get entry variables from the tuple
        self.entry_details = self.row_data[1]
        self.reference_number = self.row_data[3]
        
        layout = QHBoxLayout(self)
        
        # Create blue Edit Button
        self.edit_button = QPushButton("", self)
        self.edit_button.setStyleSheet("background-color: blue;")
        self.edit_button.setFixedSize(61, 31)
        #self.edit_button.clicked.connect(self.edit_clicked)
        
        # Create red Edit Button
        self.delete_button = QPushButton("", self)
        self.delete_button.setStyleSheet("background-color: red;")
        self.delete_button.setFixedSize(61, 31)
        
        # Set icons for the buttons
        icon = QIcon(":/icons/pencil.png")
        self.edit_button.setIcon(icon)
        
        icon2 = QIcon(":/icons/broom.png")
        self.delete_button.setIcon(icon2)
        
        layout.addWidget(self.edit_button)
        layout.addWidget(self.delete_button)
 
    '''       
    def create_connection(self):
       #replace these with your actual MySql server details
       try:
           host_name = "localhost"
           user_name = "root"
           mypassword = ""
           database_name = "reconcile"
           
           #establish a connection to MySQL server
           self.mydb = mysql.connector.connect(
               host = host_name,
               user = user_name,
               password = mypassword,
           )
           #Create a cursor to execute sql queries
           cursor = self.mydb.cursor()
           
           #Create the database if it does not exist
           cursor.execute(f'CREATE DATABASE IF NOT EXISTS {database_name}')
           
           #connect to the created database
           self.mydb = mysql.connector.connect(
               host = host_name,
               user = user_name,
               password = mypassword,
               database = database_name
           )
           
           return self.mydb
       
       except mysql.connector.Error as err:
           print(f"Database Error: {err}")
           QMessageBox.critical(None, "Database Error", f"Error: {err}")
           return None
            
   def edit_clicked(self):
        # Create an instance of Update Entry Dialog
        self.update_dialog = Ui_update_EntryDialog(self.row_index, self.row_data)
        
        # Execute the dialog
        self.update_dialog.exec()
      
        # opens the UpdateEntry Dialog
        UpdateEntryDialog = QtWidgets.QDialog()
        ui = Ui_update_EntryDialog()
        ui.setupUi(UpdateEntryDialog)
        UpdateEntryDialog.show()
        UpdateEntryDialog.exec_()
        
        #if EntryDialog.exec_() == Ui_EntryDialog.Accepted:
            
        self.load_entry_info()   
    
    
    def delete_button(self):
        pass

'''


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
