# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReconEntry.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import mysql.connector
from random import randint
from datetime import date

class Ui_ReconDialog(object):
    def setupUi(self, ReconDialog):
        ReconDialog.setObjectName("ReconDialog")
        ReconDialog.resize(567, 577)
        ReconDialog.setStyleSheet("QDialog{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left:15px;\n"
"    height:35px\n"
"}\n"
"QDateEdit{\n"
"    border: 1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left:15px;\n"
"    height:35px\n"
"}\n"
"QComboBox{\n"
"    border: 2px solid white;\n"
"    border-radius:8px;\n"
"    padding-left:15px;\n"
"    height:35px;\n"
"    padding: 1px 18px 3px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    selection-background-color: rgb(41, 128, 185);\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(ReconDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 510, 301, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addEntryBtnRecon = QtWidgets.QPushButton(self.layoutWidget, clicked = lambda: self.add_recon_entry())
        self.addEntryBtnRecon.setMinimumSize(QtCore.QSize(0, 41))
        self.addEntryBtnRecon.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.addEntryBtnRecon.setFont(font)
        self.addEntryBtnRecon.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(52, 212, 129);\n"
"    color: white;\n"
"    border:none;\n"
"    border-radius:bold;\n"
"    font-size:15px\n"
"}")
        self.addEntryBtnRecon.setObjectName("addEntryBtnRecon")
        self.horizontalLayout.addWidget(self.addEntryBtnRecon)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 41))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: #585858;\n"
"    color: white;\n"
"    border:none;\n"
"    border-radius:bold;\n"
"    font-size:15px\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.layoutWidget_2 = QtWidgets.QWidget(ReconDialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 60, 521, 429))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.dateEditRecon = QtWidgets.QDateEdit(self.layoutWidget_2, editingFinished = lambda: self.handleReconDate())
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.dateEditRecon.setFont(font)
        self.dateEditRecon.setObjectName("dateEditRecon")
        self.verticalLayout_8.addWidget(self.dateEditRecon)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.transactionComboBoxRecon = QtWidgets.QComboBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.transactionComboBoxRecon.setFont(font)
        self.transactionComboBoxRecon.setObjectName("transactionComboBoxRecon")
        self.transactionComboBoxRecon.addItem("")
        self.transactionComboBoxRecon.addItem("")
        self.verticalLayout_7.addWidget(self.transactionComboBoxRecon)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.amountLineEditRecon = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.amountLineEditRecon.setMinimumSize(QtCore.QSize(0, 35))
        self.amountLineEditRecon.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.amountLineEditRecon.setFont(font)
        self.amountLineEditRecon.setObjectName("amountLineEditRecon")
        self.verticalLayout.addWidget(self.amountLineEditRecon)
        self.verticalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.detailsLineEditRecon = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.detailsLineEditRecon.setMinimumSize(QtCore.QSize(0, 35))
        self.detailsLineEditRecon.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.detailsLineEditRecon.setFont(font)
        self.detailsLineEditRecon.setObjectName("detailsLineEditRecon")
        self.verticalLayout_4.addWidget(self.detailsLineEditRecon)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.accCodeLineEditRecon = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.accCodeLineEditRecon.setMinimumSize(QtCore.QSize(0, 35))
        self.accCodeLineEditRecon.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.accCodeLineEditRecon.setFont(font)
        self.accCodeLineEditRecon.setObjectName("accCodeLineEditRecon")
        self.verticalLayout_5.addWidget(self.accCodeLineEditRecon)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.label = QtWidgets.QLabel(ReconDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.AddReconEntry = QtWidgets.QFrame(ReconDialog)
        self.AddReconEntry.setGeometry(QtCore.QRect(10, 20, 521, 51))
        self.AddReconEntry.setFrameShape(QtWidgets.QFrame.HLine)
        self.AddReconEntry.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.AddReconEntry.setObjectName("AddReconEntry")

        self.retranslateUi(ReconDialog)
        QtCore.QMetaObject.connectSlotsByName(ReconDialog)

    def retranslateUi(self, ReconDialog):
        _translate = QtCore.QCoreApplication.translate
        ReconDialog.setWindowTitle(_translate("ReconDialog", "Recon Dialog"))
        self.addEntryBtnRecon.setText(_translate("ReconDialog", "Add Entry"))
        self.pushButton_2.setText(_translate("ReconDialog", "Cancel"))
        self.label_9.setText(_translate("ReconDialog", "Date"))
        self.label_8.setText(_translate("ReconDialog", "Transaction Type"))
        self.transactionComboBoxRecon.setItemText(0, _translate("ReconDialog", "Debit"))
        self.transactionComboBoxRecon.setItemText(1, _translate("ReconDialog", "Credit"))
        self.label_2.setText(_translate("ReconDialog", "Amount"))
        self.label_5.setText(_translate("ReconDialog", "Details"))
        self.label_6.setText(_translate("ReconDialog", "ACC Code"))
        self.label.setText(_translate("ReconDialog", "Add Recon Entry"))

    def create_connection(self):
        #replace these with your actual MySql server details
        try:
            host_name = "localhost"
            user_name = "root"
            mypassword = ""
            database_name = "reconcile"
            
            #establish a connection to MySQL server
            self.mydb = mysql.connector.connect(
                host = host_name,
                user = user_name,
                password = mypassword,
            )
            #Create a cursor to execute sql queries
            cursor = self.mydb.cursor()
            
            #Create the database if it does not exist
            cursor.execute(f'CREATE DATABASE IF NOT EXISTS {database_name}')
            
            #connect to the created database
            self.mydb = mysql.connector.connect(
                host = host_name,
                user = user_name,
                password = mypassword,
                database = database_name
            )
            
            return self.mydb
        
        except mysql.connector.Error as err:
            print(f"Database Error: {err}")
            QMessageBox.critical(None, "Database Error", f"Error: {err}")
            return None
        
    # Insert new entry
    
    def insert_recon_entry(self):
        
        try:
            connection = self.create_connection()
            if connection is None:
                return
            
            cursor = connection.cursor()
            
            transaction = self.transactionComboBoxRecon.currentText()
            reference_number = self.generate_recon_numberId(transaction)
            
            date = self.handleReconDate()
            
            # Create list of entry information
            self.new_entry = [
                date,
                self.detailsLineEditRecon.text(),
                self.accCodeLineEditRecon.text(),
                reference_number,
                self.transactionComboBoxRecon.currentText(),
                float(self.amountLineEditRecon.text()),
                
            ]
            
            # To insert multiple rows in the mysql database
            insert_entry_query = """ INSERT INTO recon_t(date, accDetails, accCode, reference_number, transaction_type, amount) VALUES (%s, %s, %s, %s, %s, %s)"""
            
            cursor.execute(insert_entry_query,self.new_entry)
            connection.commit()
            
            self.show_inserted_recon_message()
            cursor.close()
            connection.close()
            
        except mysql.connector.Error as err:
            print(f"Error: {err}")
            QMessageBox.critical(None, "Database Error", f"Error: {err}")
            
        
    def generate_recon_numberId(self, transaction):
        
        cursor = self.create_connection().cursor()
            
        while True:
            if transaction == "Credit":
                id_start_value = 'R/C'
            else:
                id_start_value = 'R/D'
                    
            random_value = self.generate_randomNumber()
            reference_number = id_start_value + random_value
                
            #check if the generated reference number is already in the table
            cursor.execute("""SELECT reference_number FROM recon_t WHERE reference_number = %s""", (reference_number,))
            existing_id = cursor.fetchone()
                
            if not existing_id:
                return reference_number
                
    def generate_randomNumber(self):
            
        number = randint(1, 1000)
        random_number = f"{number:04d}"
        return random_number
        
    def handleReconDate(self):
        
        #convert QDate to a string in the format 'YYYY-MM-DD'
        value = self.dateEditRecon.date().toPyDate()
        
        return value
        
            
    def show_inserted_recon_message(self):
            
        msg_box = QMessageBox()
        msg_box.setWindowTitle("Success")
        msg_box.setText(self.transactionComboBoxRecon.currentText() + " reconcilliation entry inserted into the database")
        msg_box.exec()
        
    def add_recon_entry(self):
        self.insert_recon_entry()
        
    def reject(self):
        self.reject()
        
      

   
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReconDialog = QtWidgets.QDialog()
    ui = Ui_ReconDialog()
    ui.setupUi(ReconDialog)
    ReconDialog.show()
    sys.exit(app.exec_())
